#!/bin/python
print("=== Анализ последовательности ДНК ===")
print()
dna = input("Последовательность ДНК: ")
dna = dna.upper()
print()
print(f"Последовательность в верхнем регистре: {dna}")
print()
print("Подсчёт нуклеотидов:")
print(f"A: {dna.count("A")}")
print(f"T: {dna.count("T")}")
print(f"G: {dna.count("G")}")
print(f"C: {dna.count("C")}")
print()
print(f"Общая длина: {len(dna)} нуклеотидов")
